name: Build Vote

on:
  push:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'

jobs:
  build-only:
    name: Vote Build (PR check)
    if: github.event_name == 'pull_request'
    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      dockerhub-enable: false
      ghcr-enable: false
      image-names: |
        ghcr.io/${{ github.repository_owner }}/voting-vote
      tag-rules: |
        type=ref,event=pr
      context: vote
      platforms: linux/amd64

  build-and-push:
    name: Vote Build and Push (main)
    if: github.event_name == 'push'
    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    with:
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/voting-vote
      tag-rules: |
        type=raw,value=latest
        type=sha
      context: vote
      platforms: linux/amd64
